### PR TITLE
Bug reporting

### PR DESCRIPTION
**Pull request by prk-dismoi**
Added bug reporting content.

### CODE REVIEW

**Review by felix-lambert — APPROVED** [review]

**Comment by lutangar** [comment]
You may see the result of your work when you click on "new issue":
https://github.com/dis-moi/mobile_poc/issues/new/choose

I don't know what was the expected result for sure but I suppose you wanted the "installation issue" and "test scenario" template to be an option when creating a new issue:

For that you'll need to include an header on both of these files:
```md
---
name: 🐛 Dismoi Android Chrome App Bug Report
about: Use this template for reporting a bug
---
```
> As seen in th the bug template file.

Just may do that on master branch since it's not critical.

In ideal world, we should have had this discussion **before** this issue was merged. 
About that:
I wasn't quick enough to react on this PR, sorry about that.
I was expecting @felix-lambert to give some feedback on this since, I suppose he'll be tho one dealing with the issues. Maybe you had this talk somewhere else, so forgive me if it's the case.

**Comment by lutangar** [comment]
Oh and I forgot to mention, we have a conventions for commit messages, see contributing guide:
https://github.com/dis-moi/.github/blob/master/CONTRIBUTING.md#git-commit-messages

I personally don't think it would wise to expect the product team to respect by the letter this convention (but you may try! <3), but it should be us, developers, to be responsible of the commits entering the project. So maybe the "merge PR" action should be done by one of us, in order to fix the commit messages if required.

**Comment by prk-dismoi** [comment]
> Oh and I forgot to mention, we have a conventions for commit messages, see contributing guide:
> https://github.com/dis-moi/.github/blob/master/CONTRIBUTING.md#git-commit-messages
> 
> I personally don't think it would wise to expect the product team to respect by the letter this convention (but you may try! <3), but it should be us, developers, to be responsible of the commits entering the project. So maybe the "merge PR" action should left to one of us, in order to fix the commit messages if required.

As long as it doesn't bring unnecessary delay, makes perfect sense to me that it stays within tech.

**Comment by prk-dismoi** [comment]
> https://github.com/dis-moi/mobile_poc/issues/new/choose

Did 2 new commits on master branch as advised.

**Comment by lutangar** [comment]
Looking good !

**Pull request merged**
