### PR TITLE
Feat/add permission name and description in the accessibility section of your android app

### PR DESCRIPTION
**Pull request by felix-lambert**
Screenshot_dismoi
Screenshot_dismoi2

Content of what has to be written in the accessibility tab of your android app

https://support.google.com/accessibility/android/answer/9078941?hl=en

### CODE REVIEW

**Comment by MaartenLMEM** [comment]
@felix-lambert 
Name : DisMoi (not Dis Moi) 
Description : you need it In English or in French ? both ?

**Comment by felix-lambert** [comment]
Ok for the name. I did'nt check the language yet. So a description in english would be perfect as a start

**Comment by MaartenLMEM** [comment]
Here is a recent description about the Add-on. I let you adapt it to the app ? 

```
Dismoi allows web users, experts, and media to post information directly on any page you browse. 
For instance :
- warning you about scams  on websites you visit
- suggesting a better choice than the product what you are checking about
- providing insights about an article you are reading
- etc.

This way, you receive their advice and information at the moment you need it.

Dismoi is a free web extension that anybody can add to their web browser (currently Chrome and Firefox)
Thanks to this extension, everyone can post information on the webpages they want.
If you follow a contributor, his information messages are displayed at the time you visit the pages he has commented on.

Freedom of information : You receive only the information of contributors you have chosen.

Each Dismoi user can also ask a question about the web page they are visiting, to which contributors may respond to.

```

**Comment by lutangar** [comment]
This is interesting. I thinks they're should be a paragraph in the doc about which permissions are requested and if they are required. (we have something similar for the extension https://github.com/dis-moi/extension#permissions)

What I am asking here might be related to the documentation effort started with @julienadamcom 
This effort should now be focus on bringing it on Github, and I think you are in position to prepare the ground and help getting this job done!

**Comment by felix-lambert** [comment]
Do we need to explain why we need to have control of the android phone in the description?

**Pull request merged**
